#ifndef TP_SO_DEBUG_H
#define TP_SO_DEBUG_H

#define DEBUG_SERVIDOR_INICIALIZA 0
#define DEBUG_SERVIDOR_CRIA_FIFO 0
#define DEBUG_CLIENTE_CRIA_FIFO 0
#define DEBUG_MUTEX_STOP_GERAL_INICIA 0
#define DEBUG_MUTEX_STOP_GERAL_COLOCA 0
#define DEBUG_GERAL_STOP 0
#define DEBUG_SERVIDOR_FIFO_ABRIR 0
#define DEBUG_CLIENTE_FIFO_ABRIR 0
#define DEBUG_CLIENTE_RECEBE_MENSAGEM 0
#define DEBUG_CLIENTE_COMANDOS 0
#define DEBUG_CLIENTE_ENVIA_HEARTBEATS 0
#define DEBUG_CLIENTE_TEMPO_AVANCA 0
#define DEBUG_CLIENTES_TIMER 0
#define DEBUG_SERVIDOR_SELL 0
#define DEBUG_ITEMS_ADD 0
#define DEBUG_SERVIDOR_BUY 0
#define DEBUG_ITEMS_CARREGA 0
#define DEBUG_SERVIDOR_LICAT 0
#define DEBUG_SERVIDOR_RECEBE_HEARTBEATS 0
#define DEBUG_SERVIDOR_ENVIA_ITEMS 0
#define DEBUG_ITEMS_LE_FICHA_INICIO 0
#define DEBUG_ITEMS_PROCURA_CATEGORIA 0
#define DEBUG_ITEMS_PROCURA_VENDEDOR 0
#define DEBUG_ITEMS_PROCURA_VALOR 0
#define DEBUG_ITEMS_PROCURA_TEMPO 0
#define DEBUG_ITEMS_MOSTRA_INFO 0
#define DEBUG_ITEM_E_LIDO 0
#define DEBUG_ITEMS_MOSTRA_LIDOS 0
#define DEBUG_ITEMS_LE_FICHA_FIM 0
#define DEBUG_COMANDOS_THREAD_CRIA 0
#define DEBUG_CLIENTES_THREAD_CRIA 0
#define DEBUG_MUTEXES 0
#define DEBUG_TEMPO_MOSTRA 0
#define DEBUG_ITEMS_TEMPO_AVANCA 0
#define DEBUG_ITEMS_REMOVE 0
#define DEBUG_ITEMS_APLICA_PROMOCAO 0
#define DEBUG_PROMOCOES 0
#define DEBUG_PROMOCOES_TEMPO_AVANCA 0
#define DEBUG_TEMPO 0
#define DEBUG_PROMOTORES 0
#define DEBUG_PROMOTORES_LE_FICHA 0
#define DEBUG_PROMOTORES_VERIFICA_ATIVOS 0
#define DEBUG_PROMOTORES_READS 0
#define DEBUG_COMANDOS 0
#define DEBUG_ITEMS_VENDA_COMPRADOR 0
#define DEBUG_ITEMS_VENDA_COMPRADOR_SALDO 0
#define DEBUG_CLIENTES_THREAD 0
#define DEBUG_CLIENTES_LOGIN 0

#define DEBUG_DESTROI_MUTEX_STOP_GERAL 0
#define DEBUG_TERMINA_FIFO_SERVIDOR 0
#define DEBUG_FIM 0

// ====================== SUCESSO ========================

#define SUCESSO 1

// ====================== FIM ========================

#define FIM 0

// ====================== ERROS ========================

#define ERRO_FIFO_SERVIDOR_JA_EXISTE -0
#define ERRO_CRIAR_FIFO -2
#define ERRO_LEITURA_FICHEIRO_CLIENTES -3
#define ERRO_NUMERO_INSUFICIENTE_CLIENTES -4
#define ERRO_ABRIR_FIFO -5
#define ERRO_VARIAVEL_AMBIENTE_FICHEIRO_ITEMS -6
#define ERRO_VARIAVEL_AMBIENTE_FICHEIRO_USERS -7
#define ERRO_VARIAVEL_AMBIENTE_FICHEIRO_PROMOTERS -8
#define ERRO_SEM_ITEMS -9
#define ERRO_CARREGAR_FICHEIRO_ITEMS -00
#define ERRO_SEM_PROMOTORES -00
#define ERRO_LEITURA_FICHEIRO_PROMOTORES -02

#endif // TP_SO_DEBUG_H

// ==================== DEBUG ======================
// printf("\n[DEBUG] -> ...\n");
// =================================================

// ==================== ERROR ======================
// printf("\n[ERROR] -> ...\n");
// =================================================